# Generated by Django 2.2.5 on 2019-09-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190923_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='children',
            new_name='parent',
        ),
    ]
